services:
  n8n:
    build: .
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - NODE_FUNCTION_ALLOW_EXTERNAL=pg
      - PORT=5555
      - NODE_ENV=production
    ports:
      - "5555:5555"
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
